### ISSUE TITLE
Loaders don't seem to always work

### ISSUE THREAD

**Issue by ascalonor** [Dysoch/DyWorld#286] opened 2019-09-27 14:26 UTC
It seems that loaders only work in certain objects.  I can get them to unload a chest, or a warehouse, but not insert into one or load/unload train cars.

**Comment by Dysoch** [comment] 2019-09-27 14:29
Train Wagons are movable objects, and are not considered a loadable object in Factorio. This can not be fixed, since its a "feature". Use Inserters to unload/load wagons into chests (warehouses are same size as a wagon, so try that) and unload from it using the loaders

Closing issue since i cant fix it, and its actually not a bug

**Closed by Dysoch** 2019-09-27 14:29 UTC
